apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE_GRAPH@microservice-blog-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-blog-graph-service
    version: 1.70.6-blog-home-prod
spec:
  type: NodePort
  selector:
    app: '${DEPLOYMENT_GRAPH@microservice-blog-config}'
  ports:
    -
      name: microservice-blog-graph-port
      port: '${INTERNAL_PORT_GRAPH@microservice-blog-config}'
